language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install
  - pipenv install coveralls codecov

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE store_manager_test_db' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
  - pytest --cov

after_success:
  - coveralls
  - codecov --token=64d68490-a7de-4bea-9b1b-1d52a961e301
